-- Task #27 (2026-08-06): public/sandbox demo firm account.
--
-- A firm flagged demo_locked shares its login credentials publicly (any
-- prospect can sign in and explore the product before creating a real
-- account). No self-serve password change works AT ALL for a demo_locked
-- firm -- neither the normal "I know the current password" path NOR the
-- emailed password-RESET path (Devin's explicit, final call: he did not
-- want "Forgot password" to work for this account even though it proves
-- control of the registered inbox). Rotating the password is an operator
-- action only (AssetLab/orchestrator does it directly on request), never
-- reachable from the public site -- see handleFirmPasswordSet()'s own
-- comment.
--
-- SSO linking is blocked outright too: a linked Google identity would let
-- whoever linked it keep signing in without the shared password at all,
-- silently undoing a password rotation meant to lock everyone else out.
ALTER TABLE firms ADD COLUMN demo_locked INTEGER NOT NULL DEFAULT 0;
